default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  database: company_house
  host: localhost
  username: postgres
  password: admin
  <<: *default

test:
  database: company_house_test
  host: localhost
  username: postgres
  password: admin
  <<: *default
